version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  test-build-push-image:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest
      - aws-ecr/build-and-push-image:
          repo: my-app
          tag: '1.0'
          requires:
            - "python/test" 